### ISSUE TITLE
Make it serverless

### ISSUE THREAD

**Issue by mmolinari** [Fumaz/haveibeenfacebooked-api#1]
Hi, I read on Reddit that you’re already working on hashing the phone numbers to avoid storing them in clear.

I would like to suggest to take a further step and avoid using a backend at all. This would give peace of mind to anyone afraid of you storing the phone numbers your users are checking.

Here’s how it could work:
- Hash the numbers
- Sort the data by hashed number
- Shard the data into different static files: those starting with “aaa”, then “aab” and so on (length of the “index” tdb, depending on length of each shard)
- when a user enters a phone number, hash it, load the related static shard on the browser and search for the hashed number

You could still save stats with an Ajax call to your server, but without sending the phone number.

This would also have another advantage: you could cache the shards on CloudFlare and reduce the bandwidth you use, and essentially scaling infinitely for free. You could actually store the whole site as a static site if you forgo the stats.

Thank you for this effort!

**Comment by tonymet** [comment]
I agree – the phone number should be hashed before sending it to the server.  If customers don't trust FB, they shouldn't have to trust you either to find out

**Comment by ajayyy** [comment]
Even better, you can submit only a hash prefix (of a required minimum length to avoid leaking the entire database), and then send back all full hashes that have that prefix. It can then check if that prefix is in the returned list.

https://en.wikipedia.org/wiki/K-anonymity#Hash-based_k-Anonymity

**Comment by MarcoBuster** [comment]
@mmolinari This is a good idea, but you don't take into account that in addition to returning whether the user is affected or not in the leak, we think it is useful to specify what data has been affected, as it is not homogeneous in the dump.

We are currently hashing all phone numbers, so the real phone number will never leave the browser.

**Comment by MarcoBuster** [comment]
The phone number hashing thing is now live. Thank you for your suggestions.
