### ISSUE TITLE
False negatives ?

### ISSUE THREAD

**Issue by bokub** [Fumaz/haveibeenfacebooked-api#2]
Hi,

Are you sure the whole dump is included in haveibeenfacebooked ?

I'm 100% sure my info has leaked, but the site says "You have not been Facebooked"...

**Comment by Ademking** [comment]
same

**Comment by MarcoBuster** [comment]
What country are you guys in? @bokub @Ademking

**Comment by Ademking** [comment]
> What country are you guys in? @bokub @Ademking

I'm from Tunisia and i think @bokub is from France

**Comment by MarcoBuster** [comment]
@Ademking Thank you, we're updating our db.

**Comment by gallypette** [comment]
I can confirm that the tool does not work for +33 phone numbers.

**Comment by digilist** [comment]
I am having the same issue in Germany (+49). According to haveibeenpwned.com my data was included in the Facebook hack.

**Comment by MarcoBuster** [comment]
Check now.

**Comment by gallypette** [comment]
I still get some false negative but now I get some hits.

**Comment by MarcoBuster** [comment]
> I still get some false negative but now I get some hits.

which countries are you getting false negatives from?

**Comment by bokub** [comment]
It works, thanks !

**Comment by Ademking** [comment]
Still not working...

**Comment by gallypette** [comment]
> > I still get some false negative but now I get some hits.
> 
> which countries are you getting false negatives from?

France +33

**Comment by bokub** [comment]
@gallypette 

Be sure **not** to include the leading 0 (your "phone number" should start with 6 or 7).

**Comment by gallypette** [comment]
> @gallypette
> 
> Be sure **not** to include the leading 0 (your "phone number" should start with 6 or 7).

sure.
