### ISSUE TITLE
Positivo con iniziali errate

### ISSUE THREAD

**Issue by Ogremoch** [Fumaz/haveibeenfacebooked-api#4]
Il numero risulta leaked ma le iniziali riportate del nome e cognome risultano sbagliate. Che tipo di problema potrebbe essere? Ho verificato una dozzina di numeri e tutti avevano le iniziali corrette, tranne il mio.

**Comment by MarcoBuster** [comment]
Abbiamo verificato alcuni numeri manualmente nel leak e siamo arrivati alla conclusione che il leak ha dati errati. Questo è buono per te, significa che qualcuno nel processo di pubblicazione ha sbagliato qualcosa e i nomi sono sbagliati.

**Comment by MarcoBuster** [comment]
Chiudo in quanto non è un problema che possiamo risolvere.
